### ISSUE TITLE
Falha no tramite, trilha de processamento ProcessarPendenciasRN.php - MySQL server has gone away

### ISSUE THREAD

**Issue by mailsonsantana** [spbgovbr/mod-sei-pen#15]
Mensagem:
MySQL server has gone away

Trilha de Processamento:
#0 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(120): InfraRN->__call('isProcedimentoR...', Array)
#1 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(120): PenTramiteProcessadoRN->isProcedimentoRecebido(141015)
#2 [internal function]: ProcessarPendenciasRN->{closure}(Object(GearmanJob), NULL)
#3 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(62): GearmanWorker->work()
#4 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(190): ProcessarPendenciasRN->processarPendencias()
#5 {main}

Detalhes:
SELECT COUNT(*) AS total  FROM md_pen_parametro WHERE md_pen_parametro.nome='PEN_ENDERECO_WEBSERVICE'

Trilha de Processamento Original:
\n0 /opt/infra/infra_php/InfraBD.php(420): InfraMySqli->consultarSql('SELECT COUNT(*)...')
\n1 /opt/sei/web/modulos/pen/rn/PenParametroRN.php(20): InfraBD->contar(Object(PenParametroDTO))
\n2 [internal function]: PenParametroRN->contarConectado(Object(PenParametroDTO))
\n3 /opt/infra/infra_php/InfraRN.php(140): call_user_func(Array, Object(PenParametroDTO))
\n4 /opt/sei/web/modulos/pen/rn/PenParametroRN.php(108): InfraRN->__call('contar', Array)
\n5 /opt/sei/web/modulos/pen/rn/PenParametroRN.php(108): PenParametroRN->contar(Object(PenParametroDTO))
\n6 /opt/sei/web/modulos/pen/rn/ProcessoEletronicoRN.php(98): PenParametroRN->getParametro('PEN_ENDERECO_WE...')
\n7 /opt/sei/web/modulos/pen/rn/PenTramiteProcessadoRN.php(121): ProcessoEletronicoRN->__construct()
\n8 /opt/sei/web/modulos/pen/rn/PenTramiteProcessadoRN.php(42): PenTramiteProcessadoRN->isTramiteRecusadoCancelado(141015)
\n9 [internal function]: PenTramiteProcessadoRN->isProcedimentoRecebidoControlado(141015)
\n10 /opt/infra/infra_php/InfraRN.php(140): call_user_func(Array, 141015)
\n11 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(120): InfraRN->__call('isProcedimentoR...', Array)
\n12 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(120): PenTramiteProcessadoRN->isProcedimentoRecebido(141015)
\n13 [internal function]: ProcessarPendenciasRN->{closure}(Object(GearmanJob), NULL)
\n14 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(62): GearmanWorker->work()
\n15 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(190): ProcessarPendenciasRN->processarPendencias()
\n16 {main}

**Comment by mailsonsantana** [comment]
Para solução foi realizado ajuste na configuração de timeout no arquivo php.ini com o Mysql.

Ativação do parametro:
mysqli.reconnect

Aumento de tempo do parâmetro:
mysql.connect_timeout

**Comment by guilhermeadc** [comment]
Obrigado pela informação Mailson, 

Estamos neste momento avaliando o problema com mais detalhes para saber o que pode ser feito para otimizar o exato ponto do erro e evitar a necessidade de modificação destes parâmetros.
