### ISSUE TITLE
Remover a validação do módulo por incompatibilidade com SEI

### ISSUE THREAD

**Issue by guilhermeadc** [spbgovbr/mod-sei-pen#150]
**Sua solicitação de melhoria está relacionada a um problema? Por favor descreva.**
A versão atual do módulo de integração do SEI com o Barramento de Serviços do PEN impede o completo funcionamento do sistema caso o módulo não esteja adequadamente configurado ou sem compatibilidade com a versão atual instalada.

-----

**Descreva a solução que você gostaria**
Modificar o mecanismo de validação das configurações e compatibilidade do módulo para somente registrar mensagens de AVISO para o administrador do sistema, através dos logs, e não impedir completamente o seu uso.

-----

**Descreva alternativas que você considerou**
Também adicionar nas notas de versão as versões do SEI compatíveis com o módulo. 

-----

**Contexto adicional**
Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de recurso aqui.

**Comment by caduvieira** [comment]
Podemos usar o DebugPen ao invés de uma Exception?
