### ISSUE TITLE
Erro ao receber processos contendo mais de um interessado com mesmo nome

### ISSUE THREAD

**Issue by guilhermecantoni** [spbgovbr/mod-sei-pen#154]
**Descreva o erro**
O módulo está gerando o erro "Foram encontrados participantes duplicados." ao receber processos de outros órgãos contendo mais de um interessado com o mesmo nome, situação aceita pelo Barramento de Serviços do PEN e encontrada em outros sistemas.

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
O problema foi reproduzido a partir do uso do sistema SUPP da AGU em que dois registros de interessados com mesmo nome foram incluídos no sistema, cada um representando um polo diferente do processo. Ao enviar o processo para o SEI, é gerado um erro durante o recebimento e o trâmite acaba sendo rejeitado e devolvido para o remetente.

-----

**Comportamento esperado**
Esperado que o processo ou documento avulso seja recebido com sucesso e que apenas um interessado com mesmo nome seja registrado no sistema.

-----

**Screenshots**
N/A

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: SEI 4.0.x
 - Navegador: Qualquer
 - Perfil do Usuário: N/A
 - Banco de dados: MySQL
-----

**Informações adicionais**
N/A

-----
**Log de Erros**
```
Trilha de Processamento:
Foram encontrados participantes duplicados.

#0 /opt/sei/web/modulos/pen/rn/ReceberProcedimentoRN.php(88): InfraRN->__call('receberProcedim...', Array)
#1 /opt/sei/web/modulos/pen/rn/ProcessarPendenciasRN.php(180): ReceberProcedimentoRN->receberProcedimento(76911)
#2 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(398): ProcessarPendenciasRN->receberProcedimento('76911')
#3 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(368): PendenciasTramiteRN->enviarPendenciaProcessamentoDireto(Object(PendenciaDTO))
#4 /opt/sei/web/modulos/pen/rn/PendenciasTramiteRN.php(95): PendenciasTramiteRN->enviarPendenciaProcessamento(Object(PendenciaDTO), false)
#5 /opt/sei/scripts/mod-pen/MonitoramentoTarefasPEN.php(30): PendenciasTramiteRN->encaminharPendencias(false, false, true)
#6 {main}
```

**Comment by guilhermeadc** [comment]
> Foram modificados 196 arquivos nesse commit. Não subiu algo a mais?

@caduvieira, foram incluídos mais arquivos sim neste commit por conta da necessidade de reorganização da estrutura de testes. Ao implementar as correções, percebi que toda a organização de testes funcionais para rodar na versão 3.1 do SEI e na 4.0 estava ruim.

Com isto, acabei fazendo uma reorganização de toda a suite de teste, separando em 2 pastas diferentes (tests_sei3 e tests_sei4). Como tive que mover arquivos e reorganizar pastas, a modificação está considerando esta quantidade grande de arquivos.

A implementação em si envolveu 3 arquivos:
- a correção propriamente dita na classe de recebimento de documentos;
- a implementação do teste funcional para o SEI 3.1
- a implementação do teste funcional para o SEI 4.0

Concordo com você que o melhor é separar esta implementação em, pelo menos, dois commits diferentes: um com a reorganização das classes de teste e outro com a correção. 

Vou aplicar eta mudança na branch antes de fazer o merge.
