### ISSUE TITLE
Compatibilidade com a versão 4.0.7

### ISSUE THREAD

**Issue by diogopaludo** [spbgovbr/mod-sei-pen#159]
Olá. Estamos instalando a versão 4.0.7 do SEI em nossa instituição e gostaríamos de atualizar o módulo de integração ao PEN, mas percebemos que no último release foi informado que há compatibilidade com as versão até 4.0.6.

Já há análise ou previsão de compatibilidade para a versão mais nova?

**Comment by guilhermeadc** [comment]
Prezado @diogopaludo ,

Estamos viabilizando a homologação do módulo para a versão 4.0.7 do SEI. 
Na última versão mod-sei-pen (3.1.15), foi removida a trava que impedia o funcionamento do módulo em versões ainda não homologadas, apresentando apenas uma mensagem de alerta no log do sistema informando que o sistema ainda não foi homologado.

**Comment by diogopaludo** [comment]
Muito obrigado pelas informações Guilherme. Instalaremos por nossa conta e risco então caso ainda não exista a compatibilidade oficial.

**Comment by caduvieira** [comment]
Issue relacionada https://github.com/spbgovbr/mod-sei-pen/issues/150
