### ISSUE TITLE
Passos para qualificação e solicitação em produção

### ISSUE THREAD

**Issue by RafaelCostaCorrea** [spbgovbr/mod-sei-pen#169]
Boa tarde pessoal, tenho uma pequena dúvida. Há 3 passos para a solicitação do certificado para o ambiente de produção, sendo eles:

1) Envio de Processo com Sucesso (Status 6);  
2) Recebimento de Processo com Sucesso (Status 6); 
3) Recusa de Processo (Status 9) pelo órgão.

Passos 1 e 2 OK. A questão é: como consigo realizar o passo 3? Não localizei no SEI como recusar um processo; também procurei nos documentos mas não consegui tirar essa dúvida.

Desde já, agradeço pela ajuda. Abraços!!

**Comment by higodf** [comment]
Prezado Rafael.

Segue o FAQ dos serviços do barramento.

https://www.gov.br/economia/pt-br/assuntos/processo-eletronico-nacional/destaques/faq/perguntas-frequentes-sobre-o-barramento

Em caso de dúvidas o canal e a Central de Atendimento do PEN.
