### ISSUE TITLE
Mensagem no log ao iniciar a fila

### ISSUE THREAD

**Issue by marlinhares** [spbgovbr/mod-sei-pen#21]
Na versao anterior, ao iniciar o supervisor, aparecia uma mensagem no log para cada worker.
- Iniciando serviço de monitoramento de pendências de trâmites de processos
- Iniciando serviço de processamento de pendências de trâmites de processos

na versao atual essas msgs nao aparecem.
Elas são muito úteis para visualizarmos rapidamente se o serviço subiu, após um restart no supervisor por ex

**Comment by jonnsl** [comment]
O log vem desativado por padrão (desde o commit https://github.com/spbgovbr/mod-sei-pen/commit/26ed7b5e22b166173b931793dc9a336160ce876a#diff-c83ff373d1fcc597750fab05e3ed982991baa9ea203c1f6edef3ec10109915c8R45) mas ainda existe. É só alterar a linha https://github.com/spbgovbr/mod-sei-pen/blob/master/src/scripts/ProcessamentoTarefasPEN.php#L28 de false pra true 
Talvez isso pudesse estar na documentação.
