### ISSUE TITLE
Problema na execução do script sei_atualizar_versao_modulo_pen.php

### ISSUE THREAD

**Issue by ajunior1** [spbgovbr/mod-sei-pen#3]
Boa tarde senhores,

Ao tentar executar o scrip em /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php ele apresenta o seguinte erro:
.
.
.
00093 - Atualizar Sequencias - Finalizado em 2.548s
00094 - CADASTRAMENTO DE AGENDAMENTO DE TAREFAS DO PEN PARA ATUALIZA▒▒O DE HIP▒TESES LEGAIS E ESP▒CIES DOCUMENTAIS
00095 - CADASTRAMENTO DE AGENDAMENTO DE TAREFAS DO PEN PARA RECEBIMENTO DE PROCESSOS DO BARRAMENTO DO SERVI▒OS DO PEN
00096 - Removendo agendamento de verifica▒▒o de servi▒os de integra▒▒o do Barramento PEN
00097 - REMO▒▒O DE COLUNAS DE DESATIVA▒▒O DE MAPEAMENTO DE ESP▒CIES N▒O MAIS UTILIZADOS
Erro atualizando VERSAO: exception 'Exception' with message ''Warning: /opt/infra/infra_php/InfraOracle.php linha:517.
oci_execute(): ORA-00972: identifier is too long
'' in /opt/infra/infra_php/Infra.php:196
Stack trace:
#0 [internal function]: infraGerarExcecao(2, 'oci_execute(): ...', '/opt/infra/infr...', 517, Array)
#1 /opt/infra/infra_php/InfraOracle.php(517): oci_execute(Resource id #1385, 32)
#2 /opt/sei/web/modulos/pen/bd/PenMetaBD.php(242): InfraOracle->executarSql('CREATE TABLE md...')
#3 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(1904): PenMetaBD->criarTabela(Array)
#4 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(85): PenAtualizarSeiRN->instalarV2000()
#5 [internal function]: PenAtualizarSeiRN->atualizarVersaoConectado()
#6 /opt/infra/infra_php/InfraRN.php(138): call_user_func(Array)
#7 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(2007): InfraRN->__call('atualizarVersao', Array)
#8 /opt/sei/scripts/mod-pen/sei_atualizar_versao_modulo_pen.php(2007): PenAtualizarSeiRN->atualizarVersao()
#9 {main}

Alguma sugestão sobre o problema? A versão do SEI utilizada na nossa instituição é a 3.1.4, tentei fazer a instalação do módulo utilizando as versões 2.0.0 beta 1 e beta 2, ambas apresentaram o erro no mesmo ponto. Obrigado pela atenção.

**Comment by guilhermeadc** [comment]
Prezado, 

Este problema foi identificado e era lançado durante a atualização no momento da criação de uma tabela temporário com um nome com 31 caracteres, ultrapassando a limitação de 30 imposta pelo Oracle.  

Este problema foi corrigido na versão 2.0.0-beta4 publicada na semana passada.
